/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_toronto_cs_cudd_CuddAdd_CubeIterator */

#ifndef _Included_edu_toronto_cs_cudd_CuddAdd_CubeIterator
#define _Included_edu_toronto_cs_cudd_CuddAdd_CubeIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_toronto_cs_cudd_CuddAdd_CubeIterator
 * Method:    firstCube
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_edu_toronto_cs_cudd_CuddAdd_00024CubeIterator_firstCube
  (JNIEnv *, jobject);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd_CubeIterator
 * Method:    nextCube
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_edu_toronto_cs_cudd_CuddAdd_00024CubeIterator_nextCube
  (JNIEnv *, jobject);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd_CubeIterator
 * Method:    freeGen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_toronto_cs_cudd_CuddAdd_00024CubeIterator_freeGen
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
