/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_toronto_cs_cudd_Cudd */

#ifndef _Included_edu_toronto_cs_cudd_Cudd
#define _Included_edu_toronto_cs_cudd_Cudd
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: log */
/* Inaccessible static: class_00024edu_00024toronto_00024cs_00024cudd_00024Cudd */
/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_toronto_cs_cudd_Cudd_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    cuddBddOnePtr
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_Cudd_cuddBddOnePtr
  (JNIEnv *, jobject);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    cuddBddZeroPtr
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_Cudd_cuddBddZeroPtr
  (JNIEnv *, jobject);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    bddVarPtr
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_Cudd_bddVarPtr
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    bddAndPtr
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_Cudd_bddAndPtr
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    bddOrPtr
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_Cudd_bddOrPtr
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    bddNotPtr
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_Cudd_bddNotPtr
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    bddConstrainPtr
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_Cudd_bddConstrainPtr
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    bddPermutePtr
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_Cudd_bddPermutePtr
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    existAbstract
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_Cudd_existAbstract
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    forallAbstract
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_Cudd_forallAbstract
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    ref
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_toronto_cs_cudd_Cudd_ref
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    deref
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_toronto_cs_cudd_Cudd_deref
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    recursiveDeref
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_toronto_cs_cudd_Cudd_recursiveDeref
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    refCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_Cudd_refCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    checkZeroRef
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_Cudd_checkZeroRef
  (JNIEnv *, jobject);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_toronto_cs_cudd_Cudd_quit
  (JNIEnv *, jobject);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    info
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_toronto_cs_cudd_Cudd_info
  (JNIEnv *, jobject);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    reorder
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_toronto_cs_cudd_Cudd_reorder
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    dagSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_Cudd_dagSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    sharingSize
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_Cudd_sharingSize
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     edu_toronto_cs_cudd_Cudd
 * Method:    transferPtr
 * Signature: (Ledu/toronto/cs/cudd/Cudd;II)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_Cudd_transferPtr
  (JNIEnv *, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
