/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_toronto_cs_cudd_CuddAdd */

#ifndef _Included_edu_toronto_cs_cudd_CuddAdd
#define _Included_edu_toronto_cs_cudd_CuddAdd
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_toronto_cs_cudd_CuddAdd_NO_VALUE
#define edu_toronto_cs_cudd_CuddAdd_NO_VALUE -1L
/* Inaccessible static: class_00024edu_00024toronto_00024cs_00024cudd_00024CuddAdd */
/* Inaccessible static: class_00024edu_00024toronto_00024cs_00024cudd_00024CuddAdd_00024ADD */
/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    init
 * Signature: (Ledu/toronto/cs/algebra/IntAlgebraWrapper;III)V
 */
JNIEXPORT void JNICALL Java_edu_toronto_cs_cudd_CuddAdd_init
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    topPtr
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_topPtr
  (JNIEnv *, jobject);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    botPtr
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_botPtr
  (JNIEnv *, jobject);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    addVarPtr
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_addVarPtr
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    addConstantPtr
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_addConstantPtr
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    addAndPtr
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_addAndPtr
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    addOrPtr
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_addOrPtr
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    addEqPtr
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_addEqPtr
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    addLeqPtr
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_addLeqPtr
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    addGeqPtr
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_addGeqPtr
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    addImplPtr
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_addImplPtr
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    addPlusPtr
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_addPlusPtr
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    addNotPtr
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_addNotPtr
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    addPermutePtr
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_addPermutePtr
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    addGetValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_addGetValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    existAbstract
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_existAbstract
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    forallAbstract
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_forallAbstract
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    addCofactorPtr
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_addCofactorPtr
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    addItePtr
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_addItePtr
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    ref
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_toronto_cs_cudd_CuddAdd_ref
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    deref
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_toronto_cs_cudd_CuddAdd_deref
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    recursiveDeref
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_toronto_cs_cudd_CuddAdd_recursiveDeref
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    isConstantPtr
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_toronto_cs_cudd_CuddAdd_isConstantPtr
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    checkZeroRef
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_checkZeroRef
  (JNIEnv *, jobject);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    gc
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_gc
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_toronto_cs_cudd_CuddAdd_quit
  (JNIEnv *, jobject);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    info
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_toronto_cs_cudd_CuddAdd_info
  (JNIEnv *, jobject);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    printMintermPtr
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_toronto_cs_cudd_CuddAdd_printMintermPtr
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    reorder
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_toronto_cs_cudd_CuddAdd_reorder
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    dagSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_dagSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    sharingSize
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_sharingSize
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     edu_toronto_cs_cudd_CuddAdd
 * Method:    dumpDaVinciPtr
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_edu_toronto_cs_cudd_CuddAdd_dumpDaVinciPtr
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
