/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.toronto.cs.tp.cvcl;


public class CVectorType {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CVectorType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected CVectorType() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      JavaCVCJNI.delete_CVectorType(swigCPtr);
    }
    swigCPtr = 0;
  }

  protected static long getCPtr(CVectorType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public CVectorType(long size) {
    this(JavaCVCJNI.new_CVectorType(size), true);
  }

  public long size() {
    return JavaCVCJNI.CVectorType_size(swigCPtr);
  }

  public boolean isEmpty() {
    return JavaCVCJNI.CVectorType_isEmpty(swigCPtr);
  }

  public void clear() {
    JavaCVCJNI.CVectorType_clear(swigCPtr);
  }

  public void add(Type x) {
    JavaCVCJNI.CVectorType_add(swigCPtr, Type.getCPtr(x));
  }

  public Type get(int i) {
    return new Type(JavaCVCJNI.CVectorType_get(swigCPtr, i), false);
  }

  public void set(int i, Type x) {
    JavaCVCJNI.CVectorType_set(swigCPtr, i, Type.getCPtr(x));
  }

}
