/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.toronto.cs.tp.cvcl;


public class Expr {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Expr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      throw new UnsupportedOperationException("C++ destructor does not have public access");
    }
    swigCPtr = 0;
  }

  protected static long getCPtr(Expr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
 
    public boolean equals (Object o)
      {
	if (o == null || !(o instanceof Expr)) return false;
	return equal (this, (Expr)o);
      }
    
    public int hashCode ()
      {
	return computeHashCode (this);
      }
    
  public java.math.BigInteger getIndex() {
    return JavaCVCJNI.Expr_getIndex(swigCPtr);
  }

  public Expr() {
    this(JavaCVCJNI.new_Expr__SWIG_0(), true);
  }

  public Expr(Expr e) {
    this(JavaCVCJNI.new_Expr__SWIG_1(Expr.getCPtr(e)), true);
  }

  public Rational getRational() {
    return new Rational(JavaCVCJNI.Expr_getRational(swigCPtr), false);
  }

  public int arity() {
    return JavaCVCJNI.Expr_arity(swigCPtr);
  }

  public int getKind() {
    return JavaCVCJNI.Expr_getKind(swigCPtr);
  }

  public Expr(ExprManager em, Op op) {
    this(JavaCVCJNI.new_Expr__SWIG_2(ExprManager.getCPtr(em), Op.getCPtr(op)), true);
  }

  public Expr(ExprManager em, Op op, Expr child) {
    this(JavaCVCJNI.new_Expr__SWIG_3(ExprManager.getCPtr(em), Op.getCPtr(op), Expr.getCPtr(child)), true);
  }

  public Expr(ExprManager em, Op op, Expr child0, Expr child1) {
    this(JavaCVCJNI.new_Expr__SWIG_4(ExprManager.getCPtr(em), Op.getCPtr(op), Expr.getCPtr(child0), Expr.getCPtr(child1)), true);
  }

  public Expr(ExprManager em, Op op, Expr child0, Expr child1, Expr child2) {
    this(JavaCVCJNI.new_Expr__SWIG_5(ExprManager.getCPtr(em), Op.getCPtr(op), Expr.getCPtr(child0), Expr.getCPtr(child1), Expr.getCPtr(child2)), true);
  }

  public Expr(ExprManager em, Op op, CVectorExpr children) {
    this(JavaCVCJNI.new_Expr__SWIG_6(ExprManager.getCPtr(em), Op.getCPtr(op), CVectorExpr.getCPtr(children)), true);
  }

  public Expr(ExprManager em, int kind) {
    this(JavaCVCJNI.new_Expr__SWIG_7(ExprManager.getCPtr(em), kind), true);
  }

  public Expr(ExprManager em, int kind, Expr child) {
    this(JavaCVCJNI.new_Expr__SWIG_8(ExprManager.getCPtr(em), kind, Expr.getCPtr(child)), true);
  }

  public Expr(ExprManager em, int kind, Expr child0, Expr child1) {
    this(JavaCVCJNI.new_Expr__SWIG_9(ExprManager.getCPtr(em), kind, Expr.getCPtr(child0), Expr.getCPtr(child1)), true);
  }

  public Expr(ExprManager em, int kind, Expr child0, Expr child1, Expr child2) {
    this(JavaCVCJNI.new_Expr__SWIG_10(ExprManager.getCPtr(em), kind, Expr.getCPtr(child0), Expr.getCPtr(child1), Expr.getCPtr(child2)), true);
  }

  public Expr(ExprManager em, int kind, CVectorExpr children) {
    this(JavaCVCJNI.new_Expr__SWIG_11(ExprManager.getCPtr(em), kind, CVectorExpr.getCPtr(children)), true);
  }

  public boolean hasOp() {
    return JavaCVCJNI.Expr_hasOp(swigCPtr);
  }

  public Expr getOp() {
    return new Expr(JavaCVCJNI.Expr_getOp(swigCPtr), false);
  }

  public boolean isFalse() {
    return JavaCVCJNI.Expr_isFalse(swigCPtr);
  }

  public boolean isTrue() {
    return JavaCVCJNI.Expr_isTrue(swigCPtr);
  }

  public boolean isBoolConst() {
    return JavaCVCJNI.Expr_isBoolConst(swigCPtr);
  }

  public boolean isVar() {
    return JavaCVCJNI.Expr_isVar(swigCPtr);
  }

  public boolean isString() {
    return JavaCVCJNI.Expr_isString(swigCPtr);
  }

  public boolean isClosure() {
    return JavaCVCJNI.Expr_isClosure(swigCPtr);
  }

  public boolean isQuantifier() {
    return JavaCVCJNI.Expr_isQuantifier(swigCPtr);
  }

  public boolean isLambda() {
    return JavaCVCJNI.Expr_isLambda(swigCPtr);
  }

  public boolean isApply() {
    return JavaCVCJNI.Expr_isApply(swigCPtr);
  }

  public boolean isRecord() {
    return JavaCVCJNI.Expr_isRecord(swigCPtr);
  }

  public boolean isRecordAccess() {
    return JavaCVCJNI.Expr_isRecordAccess(swigCPtr);
  }

  public boolean isTupleAccess() {
    return JavaCVCJNI.Expr_isTupleAccess(swigCPtr);
  }

  public int isGeneric() {
    return JavaCVCJNI.Expr_isGeneric__SWIG_0(swigCPtr);
  }

  public boolean isGeneric(int idx) {
    return JavaCVCJNI.Expr_isGeneric__SWIG_1(swigCPtr, idx);
  }

  public boolean isEq() {
    return JavaCVCJNI.Expr_isEq(swigCPtr);
  }

  public boolean isNot() {
    return JavaCVCJNI.Expr_isNot(swigCPtr);
  }

  public boolean isAnd() {
    return JavaCVCJNI.Expr_isAnd(swigCPtr);
  }

  public boolean isOr() {
    return JavaCVCJNI.Expr_isOr(swigCPtr);
  }

  public boolean isITE() {
    return JavaCVCJNI.Expr_isITE(swigCPtr);
  }

  public boolean isIff() {
    return JavaCVCJNI.Expr_isIff(swigCPtr);
  }

  public boolean isImpl() {
    return JavaCVCJNI.Expr_isImpl(swigCPtr);
  }

  public boolean isForall() {
    return JavaCVCJNI.Expr_isForall(swigCPtr);
  }

  public boolean isExists() {
    return JavaCVCJNI.Expr_isExists(swigCPtr);
  }

  public boolean isRational() {
    return JavaCVCJNI.Expr_isRational(swigCPtr);
  }

  public boolean isNull() {
    return JavaCVCJNI.Expr_isNull(swigCPtr);
  }

  public Expr eqExpr(Expr right) {
    return new Expr(JavaCVCJNI.Expr_eqExpr(swigCPtr, Expr.getCPtr(right)), true);
  }

  public Expr notExpr() {
    return new Expr(JavaCVCJNI.Expr_notExpr(swigCPtr), true);
  }

  public Expr negate() {
    return new Expr(JavaCVCJNI.Expr_negate(swigCPtr), true);
  }

  public Expr andExpr(Expr right) {
    return new Expr(JavaCVCJNI.Expr_andExpr__SWIG_0(swigCPtr, Expr.getCPtr(right)), true);
  }

  public static Expr andExpr(CVectorExpr children) {
    return new Expr(JavaCVCJNI.Expr_andExpr__SWIG_1(CVectorExpr.getCPtr(children)), true);
  }

  public Expr orExpr(Expr right) {
    return new Expr(JavaCVCJNI.Expr_orExpr__SWIG_0(swigCPtr, Expr.getCPtr(right)), true);
  }

  public static Expr orExpr(CVectorExpr children) {
    return new Expr(JavaCVCJNI.Expr_orExpr__SWIG_1(CVectorExpr.getCPtr(children)), true);
  }

  public Expr iteExpr(Expr thenpart, Expr elsepart) {
    return new Expr(JavaCVCJNI.Expr_iteExpr(swigCPtr, Expr.getCPtr(thenpart), Expr.getCPtr(elsepart)), true);
  }

  public Expr iffExpr(Expr right) {
    return new Expr(JavaCVCJNI.Expr_iffExpr(swigCPtr, Expr.getCPtr(right)), true);
  }

  public Expr impExpr(Expr right) {
    return new Expr(JavaCVCJNI.Expr_impExpr(swigCPtr, Expr.getCPtr(right)), true);
  }

  public Expr assign(Expr e) {
    return new Expr(JavaCVCJNI.Expr_assign(swigCPtr, Expr.getCPtr(e)), false);
  }

  public Expr get(int i) {
    return new Expr(JavaCVCJNI.Expr_get(swigCPtr, i), false);
  }

  public String toString() {
    return JavaCVCJNI.Expr_toString(swigCPtr);
  }

  public boolean equal(Expr e1, Expr e) {
    return JavaCVCJNI.Expr_equal(swigCPtr, Expr.getCPtr(e1), Expr.getCPtr(e));
  }

  public int computeHashCode(Expr e) {
    return JavaCVCJNI.Expr_computeHashCode(swigCPtr, Expr.getCPtr(e));
  }

}
