/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.toronto.cs.tp.cvcl;


public class Op {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Op(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected Op() {
    this(0, false);
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      throw new UnsupportedOperationException("C++ destructor does not have public access");
    }
    swigCPtr = 0;
  }

  protected static long getCPtr(Op obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public String toString() {
    return JavaCVCJNI.Op_toString(swigCPtr);
  }

  public Op(Op op) {
    this(JavaCVCJNI.new_Op__SWIG_0(Op.getCPtr(op)), true);
  }

  public Op(ExprManager em, int kind) {
    this(JavaCVCJNI.new_Op__SWIG_1(ExprManager.getCPtr(em), kind), true);
  }

  public int getKind() {
    return JavaCVCJNI.Op_getKind(swigCPtr);
  }

  public Op(int kind) {
    this(JavaCVCJNI.new_Op__SWIG_2(kind), true);
  }

  public boolean hasExpr() {
    return JavaCVCJNI.Op_hasExpr(swigCPtr);
  }

  public Expr getExpr() {
    return new Expr(JavaCVCJNI.Op_getExpr(swigCPtr), false);
  }

  public Op getOp(Expr e) {
    return new Op(JavaCVCJNI.Op_getOp(swigCPtr, Expr.getCPtr(e)), true);
  }

}
