/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.toronto.cs.tp.cvcl;


public class Rational {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Rational(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      throw new UnsupportedOperationException("C++ destructor does not have public access");
    }
    swigCPtr = 0;
  }

  protected static long getCPtr(Rational obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public Rational getNumerator() {
    return new Rational(JavaCVCJNI.Rational_getNumerator(swigCPtr), true);
  }

  public Rational getDenominator() {
    return new Rational(JavaCVCJNI.Rational_getDenominator(swigCPtr), true);
  }

  public boolean isInteger() {
    return JavaCVCJNI.Rational_isInteger(swigCPtr);
  }

  public int getInt() {
    return JavaCVCJNI.Rational_getInt(swigCPtr);
  }

  public Rational() {
    this(JavaCVCJNI.new_Rational__SWIG_0(), true);
  }

  public Rational(Rational n) {
    this(JavaCVCJNI.new_Rational__SWIG_1(Rational.getCPtr(n)), true);
  }

  public Rational(int n, int d) {
    this(JavaCVCJNI.new_Rational__SWIG_2(n, d), true);
  }

}
