/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.toronto.cs.tp.cvcl;


public class Statistics {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Statistics(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected Statistics() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      JavaCVCJNI.delete_Statistics(swigCPtr);
    }
    swigCPtr = 0;
  }

  protected static long getCPtr(Statistics obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

}
