/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.toronto.cs.tp.cvcl;


public class SWIGTYPE_p_std__vectorTstd__pairTstd__string_bool_t_t {
  private long swigCPtr;

  protected SWIGTYPE_p_std__vectorTstd__pairTstd__string_bool_t_t(long cPtr, boolean bFutureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_std__vectorTstd__pairTstd__string_bool_t_t() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_std__vectorTstd__pairTstd__string_bool_t_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

