/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.toronto.cs.tp.cvcl;


public class Theorem3 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Theorem3(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected Theorem3() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      JavaCVCJNI.delete_Theorem3(swigCPtr);
    }
    swigCPtr = 0;
  }

  protected static long getCPtr(Theorem3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public boolean isNull() {
    return JavaCVCJNI.Theorem3_isNull(swigCPtr);
  }

  public boolean isRewrite() {
    return JavaCVCJNI.Theorem3_isRewrite(swigCPtr);
  }

  public boolean isAxiom() {
    return JavaCVCJNI.Theorem3_isAxiom(swigCPtr);
  }

  public Expr getExpr() {
    return new Expr(JavaCVCJNI.Theorem3_getExpr(swigCPtr), false);
  }

  public Expr getLHS() {
    return new Expr(JavaCVCJNI.Theorem3_getLHS(swigCPtr), false);
  }

  public Expr getRHS() {
    return new Expr(JavaCVCJNI.Theorem3_getRHS(swigCPtr), false);
  }

  public Proof getProof() {
    return new Proof(JavaCVCJNI.Theorem3_getProof(swigCPtr), false);
  }

  public boolean withProof() {
    return JavaCVCJNI.Theorem3_withProof(swigCPtr);
  }

  public boolean withAssumptions() {
    return JavaCVCJNI.Theorem3_withAssumptions(swigCPtr);
  }

  public String toString() {
    return JavaCVCJNI.Theorem3_toString(swigCPtr);
  }

  public void printx() {
    JavaCVCJNI.Theorem3_printx(swigCPtr);
  }

  public void print() {
    JavaCVCJNI.Theorem3_print(swigCPtr);
  }

  public boolean isLiteral() {
    return JavaCVCJNI.Theorem3_isLiteral(swigCPtr);
  }

  public int getScope() {
    return JavaCVCJNI.Theorem3_getScope(swigCPtr);
  }

}
