/* Generated by CIL v. 1.2.5 */
/* print_CIL_Input is true */

#line 1 "test2.c"
void main(void) 
{ int x ;
  int y ;
  int z ;
  int w ;

  {
#line 7
  while (1 == 1) {
#line 8
    z = 0;
#line 9
    x = y;
#line 10
    if (w == 1) {
#line 11
      x = x + 1;
#line 12
      z = 1;
    }
#line 7
    if ( (x == y)) {
#line 7
      break;
    }
  }
#line 16
  if (z == 1) {
    ERROR: 
    goto ERROR;
  }
}
}
