/* Generated by CIL v. 1.2.5 */
/* print_CIL_Input is true */

#line 1 "foo.c"
int foo(int x ) 
{ 

  {
#line 3
  if (x == 1) {
#line 4
    return (1);
  } else {
#line 6
    return (2);
  }
}
}
#line 9 "foo.c"
void main(void) 
{ int y ;
  int *x ;
  int tmp ;

  {
#line 15
  tmp = foo(3);
#line 15
  if (tmp > 0) {
#line 16
    y --;
  }
#line 18
  while (y > 0) {
#line 20
    y --;
  }
#line 23
  y = foo(y + (*x));
#line 25
  while (y > 0) {
#line 27
    y --;
  }
#line 30
  foo(0);
#line 32
  y = foo(3);
#line 33
  return;
}
}
