/* Generated by CIL v. 1.2.5 */
/* print_CIL_Input is true */

#line 1 "test19.c"
void main(void) 
{ int x ;

  {
#line 5
  if (x > 10) {
#line 7
    while (x > 0) {
#line 8
      x --;
    }
  }
#line 12
  return;
}
}
