/* Generated by CIL v. 1.2.5 */
/* print_CIL_Input is true */

int global_y;

void main(void) 
{ int x ;

  {
  x = 3;
  if (x != 3) {
    x = x;
  } else {
    while (x > 0) {
      global_y--;
      x = x - 1;
    }
  }
  return;
}
}
