/* Generated by CIL v. 1.2.5 */
/* print_CIL_Input is true */

#line 1 "test13.c"
int main(int x ) 
{ int a ;
  int b ;

  {
#line 3
  a = 1;
#line 4
  if (a == 1) {
#line 4
    b = 1;
  } else {
#line 4
    b = 3;
  }

#line 6
  return (0);
}
}
