/* Generated by CIL v. 1.2.5 */
/* print_CIL_Input is true */

#line 1 "test21.c"
void main(void) 
{ int x ;
  int y ;

  {
#line 6
  x = 2;
#line 7
  y = 0;
#line 8
  if (y == 2) {
#line 9
    y = y + 1;
  }
#line 11
  while (x > 0) {
#line 12
    x = x - 1;
  }
#line 14
  return;
}
}
