/* Generated by CIL v. 1.2.5 */
/* print_CIL_Input is true */

#line 1 "test.c"
void main(void) 
{ int x ;
  int y ;

  {
#line 4
  x = 0;
#line 5
  y = 0;
#line 6
  x ++;
#line 7
  if (x > 0) {
#line 9
    x = x + 1;
#line 10
    y = y + 1;
  } else {
#line 13
    x = x + 1;
  }
#line 14
  y = y + 1;
#line 16
  y ++;
#line 17
  return;
}
}
