/* Generated by CIL v. 1.2.5 */
/* print_CIL_Input is true */

#line 1 "test11.c"
int main(void) 
{ int y ;

  {
#line 4
  y = 10;
#line 5
  y ++;
#line 6
  if (y == 10) {
#line 7
    y --;
  } else {
#line 9
    y ++;
  }

#line 14
  return (0);
}
}
