/* Generated by CIL v. 1.2.5 */
/* print_CIL_Input is true */

#line 1 "test15.c"
int main(void) 
{ int y ;

  {
#line 4
  y = 10;
#line 5
  if (y != 10) {
#line 6
    y = y + 1;
  } else {
#line 8
    y = y - 1;
  }

#line 13
  return (0);
}
}
