/* Generated by CIL v. 1.2.5 */
/* print_CIL_Input is true */

#line 1 "test3.c"
int main(void) 
{ int x ;
  int y ;

  {
#line 5
  x = 0;
#line 6
  y = 0;
#line 7
  while (x == y) {
#line 8
    x = x + 1;
#line 9
    y = y + 1;
  }
#line 12
  return (0);
}
}
