/* Generated by CIL v. 1.2.5 */
/* print_CIL_Input is true */


struct Irp {
   int Status ;
   int Information ;
};

struct Requests {
   int Status ;
   struct Irp *irp ;
   struct Requests *Next ;
};

struct Device {
   struct Requests *WriteListHeadVa ;
   int writeListLock ;
};

int STATUS_SUCCESS  =    0;

int STATUS_UNSUCCESSFUL  =    -1;

void FSMInit(void) 
{ 

  {

  return;
}
}

void FSMLock(void) 
{ 

  {

  return;
}
}

void FSMUnLock(void) 
{ 

  {

  return;
}
}

void SmartDevFreeBlock(struct Requests *r ) 
{ 

  {

  return;
}
}

// XXX Prototype test --- OK to leave here
void IoCompleteRequest(struct Irp *irp , int status );

void IoCompleteRequest(struct Irp *irp , int status ) 
{ 

  {

  return;
}
}

struct Device devE  ;

void main(void) 
{ int IO_NO_INCREMENT ;
  int nPacketsOld ;
  int nPackets ;
  struct Requests *request ;
  struct Irp *irp ;
  struct Device *devExt ;

  {

  IO_NO_INCREMENT = 3;

  FSMInit();

  // devExt = & devE;

  while (1 == 1) {

    FSMLock();

    nPacketsOld = nPackets;

    request = devExt->WriteListHeadVa;

    if ((unsigned int )request != (unsigned int )((struct Requests *)0)) {

      if (request->Status != 0) {

        devExt->WriteListHeadVa = request->Next;

        FSMUnLock();

        irp = request->irp;

        if (request->Status > 0) {

          irp->Status = STATUS_SUCCESS;

          irp->Information = request->Status;
        } else {

          irp->Status = STATUS_UNSUCCESSFUL;

          irp->Information = request->Status;
        }

        SmartDevFreeBlock(request);

        IO_NO_INCREMENT = 3;

        IoCompleteRequest(irp, IO_NO_INCREMENT);

        nPackets = nPackets + 1;
      }

    }

    if (! (nPackets != nPacketsOld)) {

      break;
    }
  }

  FSMUnLock();

  return;
}
}
